# config/schema.yaml

columns:
  person_age: int
  person_income: int
  person_home_ownership: object
  person_emp_length: float
  loan_intent: object
  loan_grade: object
  loan_amnt: int
  loan_int_rate: float
  loan_status: int
  loan_percent_income: float
  cb_person_default_on_file: object
  cb_person_cred_hist_length: int

target_column: loan_status
